/*
* Copyright (C) 2005 Birkbeck College University of London
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/* CVS $Id: $ */
package uk.ac.bbk.dcs.l4all.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from episode.rdf 
 * @author Auto-generated by schemagen on 09 Jan 2006 19:02 
 */
public class Episode 
{
    /**
     * Identifiers used for the nature of the episode
     */
    public static final String NATURE_FACT = "fact";
    public static final String NATURE_WISH = "wish";
    
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property url = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#url" );
    
    public static final Property owner_tmln = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#owner_tmln" );
    
    public static final Property end = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#end" );
    
    public static final Property title = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#title" );
    
    public static final Property category = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#category" );
    
    public static final Property start = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#start" );
    
    public static final Property description = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#description" );

    public static final Property nature = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#nature" );
    
    public static final Property prm_classif = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#prm_classif" );
    
    public static final Property sec_classif = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#sec_classif" );

    /** <p>An RDFS class representing a user learning trail</p> */
    public static final Resource Episode = m_model.createResource( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/episode#Episode" );
    
}
