/*
* Copyright (C) 2005 Birkbeck College University of London
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package uk.ac.bbk.dcs.l4all.vocabulary;
/* CVS $Id: L4all_ext.java,v 1.2 2005/07/04 17:52:19 gpapa05 Exp $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from l4all-ext.rdf 
 * @author Auto-generated by schemagen on 04 Jul 2005 16:33 
 */
public class L4all_ext {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-ext#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property communication_skills = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-ext#communication_skills" );
    
    public static final Property age = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-ext#age" );
    
    public static final Property password = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-ext#password" );
    
    public static final Property username = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-ext#username" );
    
    public static final Property learn_in_groups = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-ext#learn_in_groups" );
    
    public static final Property learn_alone = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-ext#learn_alone" );
    
    /** <p>Learning Style can be a choice from learning alone or learning in groups</p> */
    public static final Resource LearningStyle = m_model.createResource( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-ext#LearningStyle" );
    
}
