/*
* Copyright (C) 2005 Birkbeck College University of London
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/* CVS $Id: $ */
package uk.ac.bbk.dcs.l4all.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from l4all-user.rdf 
 * @author Auto-generated by schemagen on 17 Jan 2006 14:48 
 */
public class L4all_user {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property hours_of_study_pw = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#hours_of_study_pw" );
    
    public static final Property travel_willingness = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#travel_willingness" );
    
    public static final Property skills = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#skills" );
    
    public static final Property user_trails = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#user_trails" );
    
    public static final Property goals = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#goals" );
    
    public static final Property email = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#email" );
    
    public static final Property learning_method = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#learning_method" );
    
    public static final Property username = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#username" );
    
    public static final Property personal_desc = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#personal_desc" );
    
    public static final Property present_occupation = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#present_occupation" );
    
    public static final Property name = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#name" );
    
    public static final Property age = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#age" );
    
    public static final Property gender = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#gender" );
    
    public static final Property qualifications = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#qualifications" );
    
    public static final Property past_occupation = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#past_occupation" );
    
    public static final Property password = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#password" );
    
    public static final Property budget = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#budget" );
    
    public static final Property learning_prefs = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#learning-prefs" );
    
    public static final Property study_type = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#study_type" );
    
    public static final Property id = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#id" );
    
    public static final Property my_location = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#my-location" );
    
    public static final Property disability = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#disability" );
    
    public static final Property interests = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#interests" );

    /**
     * The access status of the user, in par with the trail's type
     * @see Trails#TYPE_USER
     * @see Trails#TYPE_EXPERT
     * @see Trails#TYPE_TEMPLATE
     */
    public static final Property status = m_model.createProperty( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#status" );

    /** <p>The class representing the learner on the system</p> */
    public static final Resource Identification = m_model.createResource( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#Identification" );
    
    /** <p>IMS LIP Goal Class</p> */
    public static final Resource Goal = m_model.createResource( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#Goal" );
    
    /** <p>The class representing the learner on the system</p> */
    public static final Resource Learner = m_model.createResource( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#Learner" );
    
    /** <p>The class representing the user qualification details</p> */
    public static final Resource QCL = m_model.createResource( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#QCL" );
    
    /** <p>The class representing the learner on the system</p> */
    public static final Resource Learning_Prefs = m_model.createResource( "http://www.dcs.bbk.ac.uk/~gpapa05/l4all/rdf/l4all-user#Learning_Prefs" );
    
}
